### ISSUE TITLE
Dependency on System.ComponentModel.Annotations < 5.0.0 casuses conflicts

### ISSUE THREAD

**Issue by weitzhandler** [OData/ModelBuilder#12]
When installing Microsoft.AspNetCore.OData, the following error occurs:

```
Restoring packages for D:\Users\Shimmy\Source\Repos\MyProject\MyProject.Api\MyProject.Api.csproj...
NU1107: Version conflict detected for System.ComponentModel.Annotations. Install/reference System.ComponentModel.Annotations 5.0.0 directly to project MyProject.Api to resolve this issue. 
 MyProject.Api -> Microsoft.EntityFrameworkCore.Tools 5.0.0 -> Microsoft.EntityFrameworkCore.Design 5.0.0 -> Microsoft.EntityFrameworkCore.Relational 5.0.0 -> Microsoft.EntityFrameworkCore 5.0.0 -> System.ComponentModel.Annotations (>= 5.0.0) 
 MyProject.Api -> Microsoft.AspNetCore.OData 8.0.0-preview2 -> Microsoft.OData.ModelBuilder 1.0.4 -> System.ComponentModel.Annotations (>= 4.6.0 && < 5.0.0).
Package restore failed. Rolling back package changes for 'MyProject.Api'.
Time Elapsed: 00:00:00.2568489
========== Finished ==========
```

### Assemblies affected

Microsoft.OData.ModelBuilder

### Reproduce steps

- Create a .NET 5 project with dependency on EF Core Tools.
- Install Microsoft.AspNetCore.OData latest preview version

### Expected result

Should not cause package conflicts

### Actual result

Causes NuGet package conflicts

### Additional detail

https://github.com/OData/ModelBuilder/blob/1e84a83ba0d1d1cef8786931aa19a7489333d137/build/builder.versions.settings.targets#L13

**Comment by xuzhg** [comment]
It's fixed in 1.0.5. Thanks.
