### ISSUE TITLE
The OData convention model builder does not recognize non-nullable reference types.

### ISSUE THREAD

**Issue by dxrdxr** [OData/ModelBuilder#16]
Developers often use OData and Entity Framework Core (EFCore) together to build services. It is frequently the case that the same data models are in shared C# code. In fact, many Microsoft OData tutorials use OData and EFCore together with shared data models. With the release of C# 8, the concept of NonNullable Reference Types (NRT) was introduced as a powerful way to strongly control nullability and greatly reduce the perennial bugs caused by dereferencing a null reference. With the release of EFCore 5, its data modeler will correctly handle NRTs.
The OData.Modelbuilder does not recognize NRTs which will cause a shared data model to have inconsistent handling of Nullability.

### Assemblies affected

OData ModelBuilder 1.0.6

### Reproduce steps

```
#nullable enable
public record Country
{
    [Key]
    [DisplayName("ISO Code")]
    [MaxLength(2)]
    [MinLength(2)]
    public string ISOCode { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
}
```
When building the EFCore and SQL database the property Name is created NOT NULL:
```
CREATE TABLE [dbo].[Country] (
[ISOCode] NVARCHAR (2)   NOT NULL,
[Name]    NVARCHAR (MAX) NOT NULL,
CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([ISOCode] ASC));
```
However, when built with the OData endpoint there is no NULLABLE=“false” facet:
```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="DSS.Models" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Country">
                <Key>
                    <PropertyRef Name="ISOCode" />
                </Key>
                <Property Name="ISOCode" Type="Edm.String" Nullable="false" MaxLength="2" />
                <Property Name="Name" Type="Edm.String" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="Countries" EntityType="DSS.Models.Country" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```
### Expected result

```
<Property Name="Name" Type="Edm.String" Nullable="false" />
```
### Actual result
```
<Property Name="Name" Type="Edm.String" />
```

### Additional detail

One straightforward workaround is to simply add a `[Required]` attribute to the `Name` property or to configure it explicitly using the model builder fluent API.
A better solution is to upgrade the OData model builder to be functionally equivalent to EFCore.

### Design Proposal

The design is heavily influenced by the implementation in EFCore, however EFCore code is structured to repeatedly ask if a type `IsNullable()`. In contrast, the OData ModelBuilder has a powerful set of conventions that are called based on the CustomAttributes in the CLR Type. This allows the OData ModelBuilder to efficiently determine an entity’s nullability as it traverses the entity sets.
It is important to note that NRTs are primarily a compiler tool for static analysis of code and generates the exact same MSIL regardless of the nullability context. But the compiler does generate two special internal only attributes `NullableAttribute` and `NullableContextAttribute` and decorates types appropriately. A complete design of the Nullable Metadata can be found [here](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md).

### `NullableAttributeEdmPropertyConvention()`
The `NullableAttribute` may appear on any CLR type that is defined within a nullable context. By creating a new `IODataModelConvention` every property can be processed and its Nullability can be set as appropriate.

For a property, the logic is straight forward:
1. If the property is already set as NonNullable, do nothing. This avoids conflict with attributes, such as `RequiredAttribute`, with a higher precedence that are called earlier.
2. If the `NullableFlags` field is not set to 1 (nonnullable), do nothing.
3. If the property’s `Get` method has the return `MaybeNullAttribute` set, do nothing.
4. Otherwise set the Nullability to be false.

### `NullableContextAttributeEdmTypeConvention()`

The `NullableContextAttribute` is an optimization used to indicate the nullability of type references that have no `NullableAttribute` annotations. It may be placed type or method declarations. The compiler has an algorithm to determine the value of the context flag, a simplistic summary is it uses the most common value in the scope.

With the OData type conventions processing, this attribute can be easily discovered on a type and applied efficiently down to its declared properties. By contrast, EFCore when processing any property without a `NullableAttribute` annotation must look up to the declaring type to determine if it has a `NullableContextAttribute` annotation that applies. This results (without a cache) in the Reflection of a type proportional to the number of declared properties. Thus, unlike EFCore, a type cache in OData is not needed.

For a type, the logic is as follows:

1. If the `NullableContextAttribute` flag is not 1, do nothing. Because the property default is Nullable.
Iterate through the properties as follows:
2. If the property is inherited, do nothing. A `NullableContextAttribute` is not inherited.
3. If the property is a value type, do nothing.
4. If the property has a `NullableAttribute` annotation, do nothing.
5. If the property’s Get method has the return `MaybeNullAttribute` set, do nothing.
6. Otherwise set the Nullability to be false.

This algorithm does not handle all possible complicated types, but matches the algorithm used by EFCore. Notable gaps include:
1. Generic types are not handled due to the very complicated semantics of the nullability of the generic type argument. Additionally, generic types are not part of the CSDL and using an instance type in a model that is derived from generic type is rare.
2. A `NullableAttribute` annotation for a complicated type (e.g., array) will have a set of flags representing elements or containing type. They are not supported due to the complexity of the nullability semantics, their relative rarity, and possibility they cannot be modeled in the CSDL.

### Extension Methods
For code reuse and cleanliness, the following extensions to `PropertyConfiguration` are created:

```
bool NonNullable()
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Returns true if the property has been set to NonNullable.

```
bool ReturnMaybeNull()
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Returns true if the property has the MaybeNull annotation.
```
void SetNonNullable()
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sets the property to be NonNullable.

### Related Issues 
#15 

### References
[https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md)

**Comment by dxrdxr** [comment]
"Docs Needed"

Documentation should be added similar to what exists in [Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#conventions).

**Comment by xuzhg** [comment]
Merged. Thanks.
