### ISSUE TITLE
Multiple entity sets mapping to one controller?

### ISSUE THREAD

**Issue by dweeden** [OData/ModelBuilder#21]
Wanting to do something very similar to this but running into the same errors.  

https://stackoverflow.com/questions/57616954/how-do-i-bind-multiple-entity-sets-to-one-odata-controller

Is there a way to do this with the current Microsoft.AspNetCore.OData 8.02?

**Comment by dweeden** [comment]
Specifically I'm trying to register the entity sets like this:

```cs
modelBuilder.EntitySet<Object>("Meta");
modelBuilder.EntitySet<Field>("Meta");
```

And then service them within my MetaController with this method

```cs
[EnableQuery]
public IActionResult Get(string name)
{
	if (name == "objects")
	{
		return Ok(_context.Objects);
        }
        else if (name == "fields")
	{
		return Ok(_context.Fields);
	}

	return NotFound();
}
```

**Comment by xuzhg** [comment]
it seems you are looking for this: https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataDynamicModel

Let me know if it's no or file new issue. thanks.
