### ISSUE TITLE
net6 DateOnly type compatability

### ISSUE THREAD

**Issue by JohnGoldInc** [OData/ModelBuilder#30]
Microsoft.OData.ModelBuilder.PrimitivePropertyConfigurationExtensions.AsDate errors on new net6 type DateOnly. 
i.e.
"The property 'DateField' on type 'Northwind.Entities.AllType' must be a System.DateTime property. (Parameter 'property')"

### Assemblies affected

OData ModelBuilder 1.0.9 and older

### Reproduce steps

Have an entity that uses DataOnly as a property type i.e.:
```
        [Column("dateField", TypeName = "date")]
        public DateOnly? DateField { get; set; }
```
### Expected result

a DateOnly property would translate to Edm.Date in ModelBuilder

### Actual result

"The property 'DateField' on type 'Northwind.Entities.AllType' must be a System.DateTime property. (Parameter 'property')"

**Comment by JohnGoldInc** [comment]
@ElizabethOkerio @xuzhg @corranrogue9 PR Still not found its way to main even though approved? 

Should I be switching to AspNetCoreOData?
https://github.com/OData/AspNetCoreOData/search?q=dateonly

**Comment by xuzhg** [comment]
Merged.

**Comment by JohnGoldInc** [comment]
@xuzhg @corranrogue9 @ElizabethOkerio can we have a pre-release please?
